### ISSUE TITLE
Check for event collisions

### ISSUE THREAD

**Issue by throughthegate** [npdoty/little-room-bot#7]
(I know it's in the code as a to do, but bringing it up since some people have double-booked the room using the bot.)

Might not be the most efficient way, but I think you could loop the `isOccupied()` function over 5 minute intervals throughout the proposed reservation to see if any of those times conflict. Might need to add another argument to the function though, or have a second similar function...

**Comment by npdoty** [comment]
Yeah, `isOccupied` just needs to be parameterized.
